### ISSUE TITLE
有时候会断开，可以写一个自动监听任务嘛，直播间开播自动去监听

### ISSUE THREAD

**Issue by lin666999** [tiangalon/dy_danmaku_java#7]

**Comment by tiangalon** [comment]
你的意思是直播间有时会断开，所以想一直挂着这个程序，等直播间恢复开播之后自动连接吗？

**Comment by lin666999** [comment]
> 你的意思是直播间有时会断开，所以想一直挂着这个程序，等直播间恢复开播之后自动连接吗？

是的，我想监听直播间内容然后把内容存储下来 比如mysql 进行用户分析，他有时候长链接失败，有时候空消息也会断开，我想看看能不能整一个继续监听什么的，
![image](https://github.com/user-attachments/assets/2d7d5a14-836f-4817-a2d2-b2c36610e71d)

**Comment by tiangalon** [comment]
可以，这个等我有空可以写一下

**Comment by lin666999** [comment]
> 可以，这个等我有空可以写一下

感谢！！！

**Comment by tiangalon** [comment]
2024/12/22 添加了自动重试功能，看下能不能满足你的需求
我这边暂时没时间做更多测试，如果有问题可以继续反馈
